name: Docker

on:
  pull_request:

env:
  IMAGE_NAME: wikijs-anyuid

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3

      - name: Identify version to tag
        run: |
          echo "IMAGE_TAG=$(fgrep "FROM ghcr.io/requarks/wiki" Dockerfile | tail -1 | cut -d@ -f1 | rev | cut -d: -f1 | rev)" >> $GITHUB_ENV

      - name: Build image
        run: docker build . --file Dockerfile
